version: "3.8"

services:
  postgres:
    container_name: postgres_test
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  
  redis:
    container_name: redis_test
    image: redis
    restart: always
    ports:
      - "6379:6379"
  
  flask-app:
    container_name: flask_app_test
    build: ./flask-app
    depends_on:
      - "postgres"
      - "redis"
    environment:
      - APP_COLOR=${APP_COLOR}
      - REDIS_USER=${REDIS_USER}
    ports:
      - "8080:8080"